<?php
$services = [
  'web-design-ux' => [
    'title' => 'Web Design & UX',
    'eyebrow' => 'Experience design',
    'headline' => 'Design that looks right because it works right.',
    'intro' => 'We combine user behaviour, information architecture, interface design and visual craft to create digital experiences that feel clear, useful and confidently on-brand.',
    'accent' => 'violet',
    'proof' => 'Design is not decoration. It is the system that helps people understand, decide and act.',
    'capabilities' => ['UX research & discovery','Information architecture','Wireframing','UI design','Responsive design','Interactive prototyping','Design systems','Developer handoff'],
    'process' => ['Research','Structure','Wireframe','Design','Prototype','Validate','Handoff'],
    'outcomes' => ['A clearer customer journey','Stronger visual credibility','Responsive screens with reusable patterns','Fewer usability dead ends','A design system ready for development'],
    'visual' => 'ux'
  ],
  'web-development' => [
    'title' => 'Web Development',
    'eyebrow' => 'Technology',
    'headline' => 'Built fast. Built clean. Built for what comes next.',
    'intro' => 'We build responsive, maintainable websites and web experiences where performance, accessibility and business logic are treated as core product decisions.',
    'accent' => 'cyan',
    'proof' => 'Good development should disappear into the experience — fast to load, easy to use and simple to maintain.',
    'capabilities' => ['Frontend development','Responsive implementation','CMS development','PHP & MySQL','API integrations','Custom web applications','Performance optimisation','Maintenance & QA'],
    'process' => ['Architecture','Components','Development','Integration','QA','Performance','Deploy'],
    'outcomes' => ['Reusable frontend components','Clean responsive behaviour','SEO-ready markup','Maintainable CMS structure','Performance and QA checkpoints'],
    'visual' => 'dev'
  ],
  'ecommerce-development' => [
    'title' => 'Ecommerce',
    'eyebrow' => 'Commerce experience',
    'headline' => 'Turn product discovery into purchase.',
    'intro' => 'We design and build ecommerce journeys around product discovery, confidence, friction reduction and repeat purchase — not just attractive storefronts.',
    'accent' => 'lime',
    'proof' => 'Every ecommerce decision should make finding, comparing and buying easier.',
    'capabilities' => ['Store strategy','Product architecture','UX & UI','Shopify / custom builds','Payments & shipping','Analytics','Conversion design','Ongoing optimisation'],
    'process' => ['Discover','Explore','Compare','Decide','Checkout','Retain'],
    'outcomes' => ['Clear product discovery','More confident decision-making','Friction-aware checkout flow','Mobile-first shopping','Measurement-ready customer journeys'],
    'visual' => 'commerce'
  ],
  'mobile-app-development' => [
    'title' => 'Mobile App Development',
    'eyebrow' => 'Digital products',
    'headline' => 'Products people do not need instructions to use.',
    'intro' => 'From user flows and prototypes to development and release support, we shape mobile experiences around simple interactions and meaningful tasks.',
    'accent' => 'orange',
    'proof' => 'The best app interface makes the next action feel obvious.',
    'capabilities' => ['Product discovery','User flows','Mobile UX/UI','Interactive prototypes','App development','API integration','Testing','Release support'],
    'process' => ['Discover','Flow','Prototype','Build','Integrate','Test','Release'],
    'outcomes' => ['Focused user journeys','Native-feeling interactions','Clear states and feedback','Scalable design patterns','Release-ready QA'],
    'visual' => 'mobile'
  ],
  'branding-creative' => [
    'title' => 'Branding & Creative',
    'eyebrow' => 'Identity systems',
    'headline' => 'Build a brand people can recognise before they read the name.',
    'intro' => 'We create practical identity systems that connect logo, typography, colour, digital assets and campaign creative into one recognisable language.',
    'accent' => 'pink',
    'proof' => 'A brand becomes valuable when every touchpoint feels connected.',
    'capabilities' => ['Brand direction','Logo systems','Typography','Colour systems','Graphic design','Marketing collateral','Social templates','Brand guidelines'],
    'process' => ['Position','Explore','Define','Systemise','Apply','Document'],
    'outcomes' => ['A coherent visual identity','Reusable brand rules','Consistent digital touchpoints','Campaign-ready assets','A scalable design system'],
    'visual' => 'brand'
  ],
  'digital-marketing' => [
    'title' => 'Digital Marketing',
    'eyebrow' => 'Growth systems',
    'headline' => 'Turn attention into measurable growth.',
    'intro' => 'We connect search, paid media, social, content and measurement around one growth plan instead of treating each channel as a separate activity.',
    'accent' => 'lime',
    'proof' => 'Marketing performs better when traffic, experience and measurement are designed together.',
    'capabilities' => ['Growth strategy','SEO','Paid media','Social media','Content planning','Landing pages','Analytics','Optimisation'],
    'process' => ['Audience','Channel','Message','Experience','Convert','Measure','Improve'],
    'outcomes' => ['Clear channel priorities','Trackable campaigns','Better landing-page alignment','Consistent messaging','Ongoing performance learning'],
    'visual' => 'growth'
  ],
  'seo' => [
    'title' => 'SEO',
    'eyebrow' => 'Search visibility',
    'headline' => 'Be useful where your customers are already searching.',
    'intro' => 'We use technical foundations, search intent, content architecture and internal linking to improve how your website is discovered and understood.',
    'accent' => 'cyan',
    'proof' => 'Useful search visibility comes from matching real intent with technically sound, well-structured content.',
    'capabilities' => ['SEO strategy','Technical SEO','Keyword & intent research','On-page SEO','Content architecture','Local SEO','Internal linking','Analytics'],
    'process' => ['Audit','Intent','Structure','Optimise','Publish','Measure','Iterate'],
    'outcomes' => ['Search-intent aligned pages','Improved crawlability','Stronger internal structure','Actionable content priorities','Measurement-ready SEO'],
    'visual' => 'seo'
  ],
  'paid-media' => [
    'title' => 'Paid Media',
    'eyebrow' => 'Performance marketing',
    'headline' => 'Spend with a reason. Optimise with evidence.',
    'intro' => 'We connect targeting, creative, landing experiences and conversion tracking so paid campaigns can be evaluated on outcomes, not clicks alone.',
    'accent' => 'orange',
    'proof' => 'A campaign is only as strong as the experience and measurement behind it.',
    'capabilities' => ['Google Search','Display','YouTube','Meta Ads','Landing pages','Creative testing','Remarketing','Conversion tracking'],
    'process' => ['Goal','Audience','Campaign','Landing','Convert','Measure','Optimise'],
    'outcomes' => ['Clear campaign objectives','Structured testing','Better message-to-page continuity','Conversion tracking','Continuous optimisation'],
    'visual' => 'paid'
  ],
  'social-media' => [
    'title' => 'Social Media',
    'eyebrow' => 'Content & community',
    'headline' => 'Show up consistently. Say something worth remembering.',
    'intro' => 'We build social systems around repeatable content pillars, useful creative, campaign moments and community feedback.',
    'accent' => 'pink',
    'proof' => 'Consistency is easier when content is designed as a system, not a daily scramble.',
    'capabilities' => ['Channel strategy','Content pillars','Creative direction','Reel concepts','Campaigns','Community guidance','Paid social','Reporting'],
    'process' => ['Position','Plan','Create','Publish','Engage','Measure'],
    'outcomes' => ['Clear content themes','Consistent visual language','Repeatable production system','Campaign-ready creative','Useful reporting'],
    'visual' => 'social'
  ],
  'reputation-management' => [
    'title' => 'Reputation Management',
    'eyebrow' => 'Trust & response',
    'headline' => 'Build trust before you need to defend it.',
    'intro' => 'We help organise review, response and monitoring workflows so customer sentiment is handled consistently and issues are surfaced early.',
    'accent' => 'violet',
    'proof' => 'Reputation is built through consistent experience, listening and response — not cosmetic suppression.',
    'capabilities' => ['Monitoring','Review strategy','Response frameworks','Brand listening','Crisis response planning','Search reputation','Reporting'],
    'process' => ['Listen','Assess','Respond','Resolve','Learn','Improve'],
    'outcomes' => ['Clear response standards','Faster issue visibility','More consistent review handling','Escalation workflows','Ongoing reputation insight'],
    'visual' => 'reputation'
  ],
  'security-testing' => [
    'title' => 'Security Testing',
    'eyebrow' => 'Web & application security',
    'headline' => 'Find weaknesses before someone else does.',
    'intro' => 'We help teams identify web and application security risks through scoped testing, prioritised reporting and remediation guidance.',
    'accent' => 'red',
    'proof' => 'Security work is most useful when findings are understandable, prioritised and actionable.',
    'capabilities' => ['Scope definition','Web application testing','Vulnerability validation','Risk classification','Reporting','Remediation guidance','Retesting'],
    'process' => ['Scope','Assess','Validate','Classify','Report','Remediate','Retest'],
    'outcomes' => ['Clear findings','Risk-based prioritisation','Actionable remediation guidance','Defined scope and evidence','Retest visibility'],
    'visual' => 'security'
  ],
];
